version: '3.8'

services:
    ECommerce:
        image: kooldev/php:8.1
        container_name: php
        working_dir: /ECommerce
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/ECommerce'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        links:
            - ECommerce-database
        depends_on:
            - ECommerce-database
    ECommerce-nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        working_dir: /ECommerce
        networks:
            - internal
            - nginx_network
        ports:
            - "9002:80"
        volumes:
            - .:/ECommerce
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - ECommerce
    ECommerce-composer:
        image: composer:latest
        container_name: composer
        working_dir: /ECommerce
        command: update --ignore-platform-reqs
        volumes:
            - .:/ECommerce
        restart: on-failure
        depends_on:
            - ECommerce
    ECommerce-database:
        image: mariadb:latest
        restart: always
        container_name: database
        working_dir: /ECommerce
        networks:
            - internal
            - nginx_network
        command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=ECommerce
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/ECommerce
            - ./ECommerce-database:/var/lib/mysql
        ports:
            - '8000:3306'
    ECommerce-redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - ECommerce-redis:/data
        networks:
            - internal
            - nginx_network
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    ECommerce-npm:
        image: node:14-alpine
        container_name: ECommerce-npm
        working_dir: /ECommerce
        volumes:
            - '.:/ECommerce'
        depends_on:
            - ECommerce

networks:
    nginx_network:
        external: true
    internal:
        driver: overlay
        name: 'global'
        attachable: true
volumes:
    ECommerce-database:
        driver: local
    ECommerce-redis:
        driver: local
